trigger: none
pr: none

pool:
  vmImage: 'windows-latest'

steps:
- task: PowerPlatformToolInstaller@2
  displayName: 'Power Platform Tool Installer '
- task: PowerPlatformPackSolution@2
  inputs:
    SolutionSourceFolder: '$(build.sourcesdirectory)\PowerPlatform\Solutions\<Solution Schemaname>'
    SolutionOutputFile: '$(Build.ArtifactStagingDirectory)\\<Solution Schemaname>_managed.zip'
    SolutionType: 'Managed'
- task: PublishPipelineArtifact@1
  displayName: Publish Artifacts
  inputs:
    targetPath: '$(Build.ArtifactStagingDirectory)'
    artifact: 'drop'
    publishLocation: 'pipeline'
