name: Build Solution

on:
  workflow_dispatch:
  
jobs:
  Build:
    runs-on: windows-latest
    steps:
      
      - uses: actions/checkout@v4

      - name: Setup MSBuild
        uses: microsoft/setup-msbuild@v1
      
      - name: Setup NuGet
        uses: NuGet/setup-nuget@v1.0.5
      
      - name: Restore Packages
        run: nuget restore MySolution.sln
      
      - name: Build solution
        run: msbuild MySolution.sln -t:rebuild -property:Configuration=Release

      - name: Run tests
        run: microsoft/vstest-action@v1.0.0

      - name: Install Power Platform Tools
        uses: microsoft/powerplatform-actions/actions-install@v1

      - name: Pack Solution
        uses: microsoft/powerplatform-actions/pack-solution@v1
        with:
          solution-file: '${{runner.temp}}/packed/DemoSolution_Managed.zip'
          solution-folder: 'PowerPlatform/Solutions/DemoSolution'
          solution-type: 'Managed'
          overwrite-files: true
          #map-file: 'PowerPlatform/Solutions/Mappings/DemoSolution.xml'

      - name: Publish Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: drop
          path: '${{runner.temp}}/packed/**'
          overwrite: true
